Eliminate ovsdb error in dsvm functional test
Meet the constraints of schema to eliminate ovsdb error log[0] cause by
passing a NoneType port_id.

[0] attempting to write bad value to column external_ids (ovsdb
error: expected string, got <type 'NoneType'>)

Change-Id: I2b0bd6bf3d4392443b24c56634c57adb03c9f72f
Signed-off-by: Dong Jun <dongj@dtdream.com>