Fix CI broke because of QoS interface and neutron DB interface changes
all_rules = qos_rule.get_rules(context, policy_id)
TypeError: get_rules() takes exactly 3 arguments (2 given)

qos_rule.get_rules() add a arguments (obj_cls) in this commit:
https://github.com/openstack/neutron/commit/6f83466307fb21aee5bb596974644d457ae1fa60#diff-94eb611a8a3b29dbf8cd2aa2466a53b9R34

This code results in a DB commit for each operation (get_object/delete_object/update_object):
https://github.com/openstack/neutron/commit/6f83466307fb21aee5bb596974644d457ae1fa60#diff-7ed10a69652bc41264bbb5ae42eb8867R526
This led to the port's revision_number increase.

Change-Id: I5186e6f2aeff19d3f8b5b3685c6babc9e905dd85
(cherry picked from commit ebb355f8a14e5ce9d88be87062ec9607b4ab83f6)